# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boliLayout.ui'
#
# Created: Tue May 29 14:28:16 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(827, 818)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Hindi, QtCore.QLocale.India))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.topPagePushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topPagePushButton.sizePolicy().hasHeightForWidth())
        self.topPagePushButton.setSizePolicy(sizePolicy)
        self.topPagePushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.topPagePushButton.setFlat(True)
        self.topPagePushButton.setObjectName(_fromUtf8("topPagePushButton"))
        self.verticalLayout.addWidget(self.topPagePushButton)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leftPagePushButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftPagePushButton.sizePolicy().hasHeightForWidth())
        self.leftPagePushButton.setSizePolicy(sizePolicy)
        self.leftPagePushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leftPagePushButton.setFlat(True)
        self.leftPagePushButton.setObjectName(_fromUtf8("leftPagePushButton"))
        self.horizontalLayout.addWidget(self.leftPagePushButton)
        self.stackedWidget = QtGui.QStackedWidget(self.widget)
        self.stackedWidget.setFrameShape(QtGui.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.outputTextEdit = QtGui.QTextEdit(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTextEdit.sizePolicy().hasHeightForWidth())
        self.outputTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.outputTextEdit.setFont(font)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.gridLayout.addWidget(self.outputTextEdit, 6, 3, 1, 1)
        self.foodPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foodPushButton.sizePolicy().hasHeightForWidth())
        self.foodPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.foodPushButton.setFont(font)
        self.foodPushButton.setObjectName(_fromUtf8("foodPushButton"))
        self.gridLayout.addWidget(self.foodPushButton, 2, 5, 1, 1)
        self.waterPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waterPushButton.sizePolicy().hasHeightForWidth())
        self.waterPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.waterPushButton.setFont(font)
        self.waterPushButton.setObjectName(_fromUtf8("waterPushButton"))
        self.gridLayout.addWidget(self.waterPushButton, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.helloPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helloPushButton.sizePolicy().hasHeightForWidth())
        self.helloPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.helloPushButton.setFont(font)
        self.helloPushButton.setObjectName(_fromUtf8("helloPushButton"))
        self.gridLayout.addWidget(self.helloPushButton, 4, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        self.happyPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.happyPushButton.sizePolicy().hasHeightForWidth())
        self.happyPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.happyPushButton.setFont(font)
        self.happyPushButton.setObjectName(_fromUtf8("happyPushButton"))
        self.gridLayout.addWidget(self.happyPushButton, 4, 5, 1, 1)
        self.yesPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yesPushButton.sizePolicy().hasHeightForWidth())
        self.yesPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.yesPushButton.setFont(font)
        self.yesPushButton.setObjectName(_fromUtf8("yesPushButton"))
        self.gridLayout.addWidget(self.yesPushButton, 2, 3, 1, 1)
        self.noPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noPushButton.sizePolicy().hasHeightForWidth())
        self.noPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.noPushButton.setFont(font)
        self.noPushButton.setObjectName(_fromUtf8("noPushButton"))
        self.gridLayout.addWidget(self.noPushButton, 4, 3, 1, 1)
        self.coldPushButton = QtGui.QPushButton(self.page)
        self.coldPushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coldPushButton.sizePolicy().hasHeightForWidth())
        self.coldPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.coldPushButton.setFont(font)
        self.coldPushButton.setObjectName(_fromUtf8("coldPushButton"))
        self.gridLayout.addWidget(self.coldPushButton, 0, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 4, 1, 1)
        self.hotPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotPushButton.sizePolicy().hasHeightForWidth())
        self.hotPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.hotPushButton.setFont(font)
        self.hotPushButton.setObjectName(_fromUtf8("hotPushButton"))
        self.gridLayout.addWidget(self.hotPushButton, 0, 1, 1, 1)
        self.kaPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kaPushButton.sizePolicy().hasHeightForWidth())
        self.kaPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.kaPushButton.setFont(font)
        self.kaPushButton.setObjectName(_fromUtf8("kaPushButton"))
        self.gridLayout.addWidget(self.kaPushButton, 0, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)
        self.cancelPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelPushButton.sizePolicy().hasHeightForWidth())
        self.cancelPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.cancelPushButton.setFont(font)
        self.cancelPushButton.setStyleSheet(_fromUtf8("background-color: rgb(161, 175, 255);"))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.gridLayout.addWidget(self.cancelPushButton, 6, 1, 1, 1)
        self.sayPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sayPushButton.sizePolicy().hasHeightForWidth())
        self.sayPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.sayPushButton.setFont(font)
        self.sayPushButton.setStyleSheet(_fromUtf8("background-color: rgb(161, 175, 255);"))
        self.sayPushButton.setObjectName(_fromUtf8("sayPushButton"))
        self.gridLayout.addWidget(self.sayPushButton, 6, 5, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_4 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 6, 0, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_2.addWidget(self.pushButton_16, 7, 3, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_2.addWidget(self.pushButton_10, 2, 2, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_2.addWidget(self.pushButton_11, 4, 2, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_2.addWidget(self.pushButton_12, 6, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_2.addWidget(self.pushButton_15, 5, 3, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_2.addWidget(self.pushButton_8, 7, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_2.addWidget(self.pushButton_7, 5, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_2.addWidget(self.pushButton_6, 3, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_2.addWidget(self.pushButton_14, 3, 3, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_2.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_2.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_2.addWidget(self.pushButton_18, 2, 4, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_2.addWidget(self.pushButton_19, 4, 4, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_2.addWidget(self.pushButton_20, 6, 4, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_2.addWidget(self.pushButton_21, 1, 5, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_2.addWidget(self.pushButton_22, 3, 5, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_2.addWidget(self.pushButton_23, 5, 5, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_2.addWidget(self.pushButton_24, 7, 5, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_2.addWidget(self.pushButton_17, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.widget_2 = QtGui.QWidget(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_25 = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.horizontalLayout_3.addWidget(self.pushButton_25)
        self.textEdit = QtGui.QTextEdit(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.pushButton_26 = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.horizontalLayout_3.addWidget(self.pushButton_26)
        self.pushButton_27 = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.horizontalLayout_3.addWidget(self.pushButton_27)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.rightPagePushButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightPagePushButton.sizePolicy().hasHeightForWidth())
        self.rightPagePushButton.setSizePolicy(sizePolicy)
        self.rightPagePushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.rightPagePushButton.setMouseTracking(False)
        self.rightPagePushButton.setAutoFillBackground(False)
        self.rightPagePushButton.setFlat(True)
        self.rightPagePushButton.setObjectName(_fromUtf8("rightPagePushButton"))
        self.horizontalLayout.addWidget(self.rightPagePushButton)
        self.verticalLayout.addWidget(self.widget)
        self.bottomPagePushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomPagePushButton.sizePolicy().hasHeightForWidth())
        self.bottomPagePushButton.setSizePolicy(sizePolicy)
        self.bottomPagePushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.bottomPagePushButton.setFlat(True)
        self.bottomPagePushButton.setObjectName(_fromUtf8("bottomPagePushButton"))
        self.verticalLayout.addWidget(self.bottomPagePushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Boli", None, QtGui.QApplication.UnicodeUTF8))
        self.topPagePushButton.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.leftPagePushButton.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.outputTextEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lohit Hindi\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:medium; color:#000000;\">हेल्लो </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.foodPushButton.setText(QtGui.QApplication.translate("MainWindow", "खाना", None, QtGui.QApplication.UnicodeUTF8))
        self.waterPushButton.setText(QtGui.QApplication.translate("MainWindow", "पानी", None, QtGui.QApplication.UnicodeUTF8))
        self.helloPushButton.setText(QtGui.QApplication.translate("MainWindow", "हेल्लो ", None, QtGui.QApplication.UnicodeUTF8))
        self.happyPushButton.setText(QtGui.QApplication.translate("MainWindow", "खुश", None, QtGui.QApplication.UnicodeUTF8))
        self.yesPushButton.setText(QtGui.QApplication.translate("MainWindow", "हां", None, QtGui.QApplication.UnicodeUTF8))
        self.noPushButton.setText(QtGui.QApplication.translate("MainWindow", "ना", None, QtGui.QApplication.UnicodeUTF8))
        self.coldPushButton.setText(QtGui.QApplication.translate("MainWindow", "सरदी", None, QtGui.QApplication.UnicodeUTF8))
        self.hotPushButton.setText(QtGui.QApplication.translate("MainWindow", "गरमि", None, QtGui.QApplication.UnicodeUTF8))
        self.kaPushButton.setText(QtGui.QApplication.translate("MainWindow", "क", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("MainWindow", "वापस", None, QtGui.QApplication.UnicodeUTF8))
        self.sayPushButton.setText(QtGui.QApplication.translate("MainWindow", "बोल", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "ज", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MainWindow", "व", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "प", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("MainWindow", "ब", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MainWindow", "म", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "च", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow", "ल", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "द", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "क", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "त", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "ड", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "ट", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MainWindow", "र", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "न", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MainWindow", "य", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "ग", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("MainWindow", "स", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("MainWindow", "ह", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("MainWindow", "अ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("MainWindow", "इ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("MainWindow", "उ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("MainWindow", "ए", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("MainWindow", "ओ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MainWindow", "ष", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_25.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_26.setText(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_27.setText(QtGui.QApplication.translate("MainWindow", "Say", None, QtGui.QApplication.UnicodeUTF8))
        self.rightPagePushButton.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomPagePushButton.setText(QtGui.QApplication.translate("MainWindow", "v", None, QtGui.QApplication.UnicodeUTF8))

