# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boliLayout.ui'
#
# Created: Tue May  8 14:01:32 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Hindi, QtCore.QLocale.India))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.outputTextEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTextEdit.sizePolicy().hasHeightForWidth())
        self.outputTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.outputTextEdit.setFont(font)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.gridLayout.addWidget(self.outputTextEdit, 6, 3, 1, 1)
        self.foodPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foodPushButton.sizePolicy().hasHeightForWidth())
        self.foodPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.foodPushButton.setFont(font)
        self.foodPushButton.setObjectName(_fromUtf8("foodPushButton"))
        self.gridLayout.addWidget(self.foodPushButton, 2, 5, 1, 1)
        self.waterPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waterPushButton.sizePolicy().hasHeightForWidth())
        self.waterPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.waterPushButton.setFont(font)
        self.waterPushButton.setObjectName(_fromUtf8("waterPushButton"))
        self.gridLayout.addWidget(self.waterPushButton, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.helloPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helloPushButton.sizePolicy().hasHeightForWidth())
        self.helloPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.helloPushButton.setFont(font)
        self.helloPushButton.setObjectName(_fromUtf8("helloPushButton"))
        self.gridLayout.addWidget(self.helloPushButton, 4, 1, 1, 1)
        self.happyPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.happyPushButton.sizePolicy().hasHeightForWidth())
        self.happyPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.happyPushButton.setFont(font)
        self.happyPushButton.setObjectName(_fromUtf8("happyPushButton"))
        self.gridLayout.addWidget(self.happyPushButton, 4, 5, 1, 1)
        self.yesPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yesPushButton.sizePolicy().hasHeightForWidth())
        self.yesPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.yesPushButton.setFont(font)
        self.yesPushButton.setObjectName(_fromUtf8("yesPushButton"))
        self.gridLayout.addWidget(self.yesPushButton, 2, 3, 1, 1)
        self.noPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noPushButton.sizePolicy().hasHeightForWidth())
        self.noPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.noPushButton.setFont(font)
        self.noPushButton.setObjectName(_fromUtf8("noPushButton"))
        self.gridLayout.addWidget(self.noPushButton, 4, 3, 1, 1)
        self.coldPushButton = QtGui.QPushButton(self.centralwidget)
        self.coldPushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coldPushButton.sizePolicy().hasHeightForWidth())
        self.coldPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.coldPushButton.setFont(font)
        self.coldPushButton.setObjectName(_fromUtf8("coldPushButton"))
        self.gridLayout.addWidget(self.coldPushButton, 0, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.hotPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotPushButton.sizePolicy().hasHeightForWidth())
        self.hotPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.hotPushButton.setFont(font)
        self.hotPushButton.setObjectName(_fromUtf8("hotPushButton"))
        self.gridLayout.addWidget(self.hotPushButton, 0, 1, 1, 1)
        self.kaPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kaPushButton.sizePolicy().hasHeightForWidth())
        self.kaPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.kaPushButton.setFont(font)
        self.kaPushButton.setObjectName(_fromUtf8("kaPushButton"))
        self.gridLayout.addWidget(self.kaPushButton, 0, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 5, 1, 1, 1)
        self.cancelPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelPushButton.sizePolicy().hasHeightForWidth())
        self.cancelPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.cancelPushButton.setFont(font)
        self.cancelPushButton.setStyleSheet(_fromUtf8("background-color: rgb(161, 175, 255);"))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.gridLayout.addWidget(self.cancelPushButton, 6, 1, 1, 1)
        self.sayPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sayPushButton.sizePolicy().hasHeightForWidth())
        self.sayPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lohit Hindi"))
        font.setPointSize(36)
        self.sayPushButton.setFont(font)
        self.sayPushButton.setStyleSheet(_fromUtf8("background-color: rgb(161, 175, 255);"))
        self.sayPushButton.setObjectName(_fromUtf8("sayPushButton"))
        self.gridLayout.addWidget(self.sayPushButton, 6, 5, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Boli", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.outputTextEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lohit Hindi\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:medium; color:#000000;\">हेल्लो </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.foodPushButton.setText(QtGui.QApplication.translate("MainWindow", "खाना", None, QtGui.QApplication.UnicodeUTF8))
        self.waterPushButton.setText(QtGui.QApplication.translate("MainWindow", "पानी", None, QtGui.QApplication.UnicodeUTF8))
        self.helloPushButton.setText(QtGui.QApplication.translate("MainWindow", "हेल्लो ", None, QtGui.QApplication.UnicodeUTF8))
        self.happyPushButton.setText(QtGui.QApplication.translate("MainWindow", "खुश", None, QtGui.QApplication.UnicodeUTF8))
        self.yesPushButton.setText(QtGui.QApplication.translate("MainWindow", "हां", None, QtGui.QApplication.UnicodeUTF8))
        self.noPushButton.setText(QtGui.QApplication.translate("MainWindow", "ना", None, QtGui.QApplication.UnicodeUTF8))
        self.coldPushButton.setText(QtGui.QApplication.translate("MainWindow", "सरदी", None, QtGui.QApplication.UnicodeUTF8))
        self.hotPushButton.setText(QtGui.QApplication.translate("MainWindow", "गरमि", None, QtGui.QApplication.UnicodeUTF8))
        self.kaPushButton.setText(QtGui.QApplication.translate("MainWindow", "क", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("MainWindow", "वापस", None, QtGui.QApplication.UnicodeUTF8))
        self.sayPushButton.setText(QtGui.QApplication.translate("MainWindow", "बोल", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))

