# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boliLayout.ui'
#
# Created: Tue May  1 21:02:25 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

#Author:Chaitanya CH
#FileName: boliLayout.py

#This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.foodPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foodPushButton.sizePolicy().hasHeightForWidth())
        self.foodPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.foodPushButton.setFont(font)
        self.foodPushButton.setObjectName(_fromUtf8("foodPushButton"))
        self.gridLayout.addWidget(self.foodPushButton, 2, 4, 1, 1)
        self.waterPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waterPushButton.sizePolicy().hasHeightForWidth())
        self.waterPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.waterPushButton.setFont(font)
        self.waterPushButton.setObjectName(_fromUtf8("waterPushButton"))
        self.gridLayout.addWidget(self.waterPushButton, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.helloPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helloPushButton.sizePolicy().hasHeightForWidth())
        self.helloPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.helloPushButton.setFont(font)
        self.helloPushButton.setObjectName(_fromUtf8("helloPushButton"))
        self.gridLayout.addWidget(self.helloPushButton, 4, 0, 1, 1)
        self.happyPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.happyPushButton.sizePolicy().hasHeightForWidth())
        self.happyPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.happyPushButton.setFont(font)
        self.happyPushButton.setObjectName(_fromUtf8("happyPushButton"))
        self.gridLayout.addWidget(self.happyPushButton, 4, 4, 1, 1)
        self.yesPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yesPushButton.sizePolicy().hasHeightForWidth())
        self.yesPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(36)
        self.yesPushButton.setFont(font)
        self.yesPushButton.setObjectName(_fromUtf8("yesPushButton"))
        self.gridLayout.addWidget(self.yesPushButton, 2, 2, 1, 1)
        self.noPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noPushButton.sizePolicy().hasHeightForWidth())
        self.noPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.noPushButton.setFont(font)
        self.noPushButton.setObjectName(_fromUtf8("noPushButton"))
        self.gridLayout.addWidget(self.noPushButton, 4, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.coldPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coldPushButton.sizePolicy().hasHeightForWidth())
        self.coldPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.coldPushButton.setFont(font)
        self.coldPushButton.setObjectName(_fromUtf8("coldPushButton"))
        self.gridLayout.addWidget(self.coldPushButton, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.hotPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hotPushButton.sizePolicy().hasHeightForWidth())
        self.hotPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.hotPushButton.setFont(font)
        self.hotPushButton.setObjectName(_fromUtf8("hotPushButton"))
        self.gridLayout.addWidget(self.hotPushButton, 0, 0, 1, 1)
        self.kaPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kaPushButton.sizePolicy().hasHeightForWidth())
        self.kaPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.kaPushButton.setFont(font)
        self.kaPushButton.setObjectName(_fromUtf8("kaPushButton"))
        self.gridLayout.addWidget(self.kaPushButton, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)
        self.cancelPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelPushButton.sizePolicy().hasHeightForWidth())
        self.cancelPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cancelPushButton.setFont(font)
        self.cancelPushButton.setStyleSheet(_fromUtf8("background-color: rgb(161, 175, 255);"))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.gridLayout.addWidget(self.cancelPushButton, 6, 0, 1, 1)
        self.sayPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sayPushButton.sizePolicy().hasHeightForWidth())
        self.sayPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.sayPushButton.setFont(font)
        self.sayPushButton.setStyleSheet(_fromUtf8("background-color: rgb(161, 175, 255);"))
        self.sayPushButton.setObjectName(_fromUtf8("sayPushButton"))
        self.gridLayout.addWidget(self.sayPushButton, 6, 4, 1, 1)
        self.outputTextEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTextEdit.sizePolicy().hasHeightForWidth())
        self.outputTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputTextEdit.setFont(font)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.gridLayout.addWidget(self.outputTextEdit, 6, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Boli", None, QtGui.QApplication.UnicodeUTF8))
        self.foodPushButton.setText(QtGui.QApplication.translate("MainWindow", "Food", None, QtGui.QApplication.UnicodeUTF8))
        self.waterPushButton.setText(QtGui.QApplication.translate("MainWindow", "Water", None, QtGui.QApplication.UnicodeUTF8))
        self.helloPushButton.setText(QtGui.QApplication.translate("MainWindow", "Hello", None, QtGui.QApplication.UnicodeUTF8))
        self.happyPushButton.setText(QtGui.QApplication.translate("MainWindow", "Happy", None, QtGui.QApplication.UnicodeUTF8))
        self.yesPushButton.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.noPushButton.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.coldPushButton.setText(QtGui.QApplication.translate("MainWindow", "Cold", None, QtGui.QApplication.UnicodeUTF8))
        self.hotPushButton.setText(QtGui.QApplication.translate("MainWindow", "Hot", None, QtGui.QApplication.UnicodeUTF8))
        self.kaPushButton.setText(QtGui.QApplication.translate("MainWindow", "KA", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.sayPushButton.setText(QtGui.QApplication.translate("MainWindow", "Say", None, QtGui.QApplication.UnicodeUTF8))
        self.outputTextEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hello</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

